# Generated by Django 4.0 on 2023-06-26 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_remove_assignment_agent_remove_assignment_function_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Want_To_Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('MASCULIN', 'masculin'), ('FEMININ', 'féminin'), ('AUTRES', 'autres')], max_length=25)),
                ('is_finish', models.BooleanField(default=False)),
                ('is_cancel', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('picture', models.ImageField(blank=True, max_length=255, null=True, upload_to='Images/Datasource')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Population_Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_issued', models.CharField(max_length=255)),
                ('reason_to_certify', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(max_length=255)),
                ('latittude', models.CharField(max_length=255)),
                ('is_finish', models.BooleanField(default=False)),
                ('is_cancel', models.BooleanField(default=False)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Curfew_And_Instability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('latittude', models.CharField(max_length=255)),
                ('is_finish', models.BooleanField(default=False)),
                ('is_cancel', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, max_length=255, null=True, upload_to='Images/Curfew_And_Instability')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.user')),
            ],
        ),
    ]
