# Generated by Django 4.0 on 2023-06-27 10:01

from django.db import migrations, models
import django.db.models.deletion
import security_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_profile_picture'),
        ('security_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curfew_and_instability',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=security_data.models.get_image_path_cai),
        ),
        migrations.AlterField(
            model_name='want_to_research',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=security_data.models.get_image_path_wtr),
        ),
        migrations.CreateModel(
            name='Try_Recognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.user')),
            ],
        ),
    ]
