# Generated by Django 4.0 on 2023-06-29 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_data', '0002_alter_curfew_and_instability_picture_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Try_Recognition',
        ),
    ]
