# Generated by Django 4.0 on 2023-06-29 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security_data', '0003_delete_try_recognition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recognized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('latittude', models.CharField(max_length=255)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('wtr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='security_data.want_to_research')),
            ],
        ),
    ]
