# Generated by Django 4.0 on 2023-06-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_data', '0004_recognized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognized',
            name='latittude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recognized',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
