# Generated by Django 4.0 on 2023-06-26 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='function',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='buy_mode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='function',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='station',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='agent',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Buy_Mode',
        ),
        migrations.DeleteModel(
            name='Function',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.DeleteModel(
            name='Usage',
        ),
    ]
